### ISSUE TITLE
Laravel 5.2 compatibility

### ISSUE THREAD

**Issue by poisa** [kamranahmedse/laravel-faulty#1]
I'm trying to use this with Laravel 5.2 and cannot get it to work. 

`KamranAhmed\Faulty\Handler` is trying to extend `Laravel\Lumen\Exceptions\Handler` which does not exist in the Laravel 5.2 code base. Maybe this was intended for an earlier version of Laravel?

**Comment by rafael-iop** [comment]
I have this issue with Laravel 5.3 too.

**Comment by poisa** [comment]
Hey, I ended up realizing that this was not meant for Laravel but for Laravel/Lumen which is their microframework. I switched to https://github.com/nilportugues/php-api-problems for my app. Note that with that package you will also need to install "symfony/psr-http-message-bridge".

**Comment by kamranahmedse** [comment]
Hey guys, thank you for reporting the issue, I will fix it this weekend or maybe before.
